### ISSUE TITLE
Custom time range

### ISSUE THREAD

**Issue by salvq** [WilliamVenner/grafana-timepicker-buttons#1]
I found your approach very intereseting and would be even better :) if possible to add below time frames. It is more less feature request, is it possible to set buttons the way I describe below ?

This would be very helpful and many users would benefit from that, that was the initial request from [Custom Time ranges to the time picker drop down](https://github.com/grafana/grafana/issues/2417)

**Yesterday: all shifts**
yesterday from 06:00 to today 06:00

**Yesterday: 1st shift =** 
yesterday from 06:00 to 14:00

**Today: 1st shift**
today from 06:00 to 14:00

etc.

**Comment by WilliamVenner** [comment]
The time ranges can only be determined through your datasource. To generate dynamic time ranges you'll need to connect to a (for example) MySQL datasource and use functions like [these](https://dev.mysql.com/doc/refman/5.5/en/date-and-time-functions.html).

**Comment by WilliamVenner** [comment]
Also, the accepted time ranges can be [moment.js date formats](https://momentjs.com/docs/), too. You might be able to construct something like that via moment.js.
