### ISSUE TITLE
InfluxDB and Timepicker-buttons

### ISSUE THREAD

**Issue by KOCIU22** [WilliamVenner/grafana-timepicker-buttons#10]
Does the plugin work with Influx databases? if so how to use it or configure it?

Best Regards Luke

**Comment by WilliamVenner** [comment]
Yes it should be.

Configuration would be very similar to how you would configure it with any other datasource.

**Comment by WilliamVenner** [comment]
I believe #7 confirms that InfluxDB works with the plugin, at least in version >=3.0.0.

**Comment by yujia21** [comment]
Adding some info in case it could help others - it's not super straightforward to query the time column in influxDB with this plugin, but for Grafana 8, once you get your time series with your query as a table, you can use Transforms to add a binary operation that sums the time column with 0 which results in a column of timestamps in unix (which you can then reduce to get the first and last timestamp, for example).
