### ISSUE TITLE
Dynamic date

### ISSUE THREAD

**Issue by KOCIU22** [WilliamVenner/grafana-timepicker-buttons#12]
Hello

I would like to configure myself three buttons with a time range for three working shifts, e.g.

1 Shift from 06:00 to 14:00
2 Shift from 14:00 to 22:00
3 Shift from 22:00 to 06:00

But the date had to be dynamic, always the current day, is it possible to add such functionality or maybe it can be done now in the current plugin version, if so, if not, is it possible at all?

**Comment by WilliamVenner** [comment]
Grafana has a huge range of datasources that are capable of returning the current time, an example in MySQL for 1 would be:

```sql
SELECT
    UNIX_TIMESTAMP(DATE(NOW()) + INTERVAL 6 HOUR) as 'time_from',
    UNIX_TIMESTAMP(DATE(NOW()) + INTERVAL 14 HOUR) as 'time_to'
```

**Comment by KOCIU22** [comment]
> Grafana has a huge range of datasources that are capable of returning the current time, an example in MySQL for 1 would be:
> 
> ```sql
> SELECT
>     UNIX_TIMESTAMP(DATE(NOW()) + INTERVAL 6 HOUR) as 'time_from',
>     UNIX_TIMESTAMP(DATE(NOW()) + INTERVAL 14 HOUR) as 'time_to'
> ```

OK but how to use it in Influx ?

**Comment by WilliamVenner** [comment]
I don't know, I've never used InfluxDB. I'm sure the answer is out there.

**Comment by KOCIU22** [comment]
Ok, I use sql like you and it works, but how do you set the automatic refreshing of the dashboard, after clicking the "change" button, the time is dynamically set but the dashboard does not refresh, can you add this function?
