### ISSUE TITLE
Plugin crashes on Grafana 7.1 

### ISSUE THREAD

**Issue by rovegrod** [WilliamVenner/grafana-timepicker-buttons#4]
Dear developers, 

I'm having problems trying to make your plugin works on Grafana 7.1, is this version supported? 

If it helps you here you have a screenshot from my browser debug console: 
![Screenshot 2020-08-13 at 15 50 54](https://user-images.githubusercontent.com/50721154/90142871-32229880-dd7d-11ea-9eaf-6972291b16f5.png)

**Comment by WilliamVenner** [comment]
Hi, I believe the last version this plugin worked with was Grafana 6.

**Comment by rovegrod** [comment]
Yes, I made it work on 6.7.4 a few months ago but now even on this version the plugin crashes. Which version are you using?
Same error that in version 7.1:
<img width="673" alt="Screenshot 2020-08-13 at 17 55 57" src="https://user-images.githubusercontent.com/50721154/90158345-2fc93a00-dd8f-11ea-9a72-ed8964cb16c4.png">
<img width="721" alt="Screenshot 2020-08-13 at 17 56 48" src="https://user-images.githubusercontent.com/50721154/90158353-335cc100-dd8f-11ea-9259-937beb6ce2b0.png">

And thanks for your quick answer!

**Comment by WilliamVenner** [comment]
Use this for now

https://github.com/WilliamVenner/grafana-timepicker-buttons/tree/a4a8a068c8b8001719e34ce05522677c461957b8

**Comment by rovegrod** [comment]
> Use this for now
> 
> https://github.com/WilliamVenner/grafana-timepicker-buttons/tree/a4a8a068c8b8001719e34ce05522677c461957b8

Thanks a lot! Works fine.

**Comment by WilliamVenner** [comment]
Plugin now works for Grafana 7.
