### ISSUE TITLE
to = from when time_to is set

### ISSUE THREAD

**Issue by beatricecoldewey** [WilliamVenner/grafana-timepicker-buttons#5]
Hey,

when I set a time_to the to is set to the same value as from. The values offered by the query are different (seen in Query Inspector).

I can't really determine why. Can you help?

Tested with Grafana 7.0.3 and 7.2.1 with Timepicker-Buttons 2.0.0.

Thank you in advance!

**Comment by WilliamVenner** [comment]
Fixed in https://github.com/WilliamVenner/grafana-timepicker-buttons/commit/99241edd3a8f9fd83f11464b5cd0e7724e57eb95
