### ISSUE TITLE
Dropdown list feature available?

### ISSUE THREAD

**Issue by Antoine-D6** [WilliamVenner/grafana-timepicker-buttons#6]
Dear,

I recently implement this plugin and I love it !
My (future) users are non-technical and grafana standard time range chooser is too complex.
I am now able to let them choose (in native language !) their time range in my predifined choices.
Thansk a lot.

I would like to suggest an enhancement. Let me know if it is possible:
I have a dashboard and analysis is weekly based. Today I am using buttons so the user can select the week they want to analyse.
However, There can be 52 choices in the future so would be great to be able to propose a scrolldown list instead of individual buttons.

Best Regards,
Antoine

**Comment by WilliamVenner** [comment]
Closed by #9 thanks to @jburgess
